export const projects = [
  {
    title: 'Amazon CLONE',
    description: "Using Next JS, FireBase ,Stripe and Tailwind CSS, I built an ECommerce App WITH payment functionality.",
      image: '/images/Amazon.jpg',
      tags: ['Next JS,', 'FireBase,', 'Stripe,', 'Tailwind CSS,' , 'Server Side Rendering'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Crypto Bot',
    description: "An internal project, built on my internship. Using Node JS, AWS and various trading API's to buy from 1 exchange and sell on another. Built with another developer.",
      image: '/images/CryptoBot.jpg',
      tags: ['Node JS,', 'AWS Dynamo DB,', 'AWS Lambda,', 'AWS Lightsail,', "Trading API's"],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'MiTunes.tv',
    description: "I worked on this website while on an internship, making frontend and backend fixes.",
      image: '/images/MiTunes.jpg',
      tags: ['Meteor JS', 'React JS'],
    source: '',
    id: 8,
  },
  {
    title: 'Blog Post Scraper/Data Visualization Tool',
    description: "This one was more for my own personal use than anything else. While volunteering at TheNibbleByte, there was limited analytic tools. I created a Selenium scraper to fetch the number of views, then using NumPy and SeaBorn to plot them on a graph to create a trend line.",
      image: '/images/DataVisualization.jpg',
      tags: ['Node JS,', 'AWS Dynamo DB,', 'AWS Lambda,', 'AWS Lightsail,', "Trading API"],
    source: 'https://github.com/vikramnayyarcs/Automation-Scraping',
    id: 3,
  },
  {
    title: 'Netflix CLONE',
    description: "This uses similar technologies to the Amazon CLONE, but the difference is that with Stripe, we used subscription payments this time!",
      image: '/images/Netflix.png',
      tags: ['React JS,', 'REDUX,', 'Stripe Subscription Payments'],
    source: 'https://github.com/vikramnayyarcs/Automation-Scraping',
    id: 4,
  },
  {
    title: 'AI Object Detector (HaarCascade)',
    description: "Using the HaarCascade Algorithm to detect objects such as faces, eyes, number plates and eyes.",
      image: '/images/Haarcascade.jpg',
      tags: ['Python,', 'HaarCascade Algorithm'],
    source: 'https://github.com/vikramnayyarcs/Assisted-Builds/tree/master/Python/AI%20Face%20Detection',
    id: 5,
  },
  {
    title: 'WhatsApp CLONE',
    description: "WhatsApp CLONE with PRIVATE CHATS! ",
      image: '/images/Whatsapp.png',
      tags: ['NEXT JS,', 'Styled Components,', 'Google  Authentication,', 'Server Side Rendering'],
    source: 'https://github.com/vikramnayyarcs/Automation-Scraping',
    id: 6,
  },
  {
    title: 'Facebook CLONE',
    description: "Facebook clone using Next JS and Tailwind CSS.",
      image: '/images/Facebook.png',
      tags: ['Next JS', 'Tailwind CSS'],
    source: '',
    id: 7,
  },
  {
    title: 'Gmail CLONE',
    description: "",
      image: '/images/Gmail.png',
      tags: ['React JS', 'REDUX', 'Styled Components'],
    source: '',
    id: 9,
  },
  {
    title: 'Snapchat CLONE',
    description: "",
      image: '/images/Snapchat.jpg',
      tags: ['React JS', 'React Camera', 'FireBase'],
    source: '',
    id: 10,
  },
  {
    title: 'LinkedIn CLONE',
    description: "",
      image: '/images/LinkedIn.png',
      tags: ['React JS', 'FireBase CSS'],
    source: '',
    id: 11,
  },
  
];

export const TimeLineData = [
  { year: 2017, text: 'Started off with "Hello World"!', },
  { year: 2018, text: 'Started gaining qualifications in Computer Science!', },
  { year: 2019, text: 'Delved into Android Development!', },
  { year: 2020, text: 'Started my own platform, documenting the journey!'},
  { year: 2021, text: 'Landed my 1st internship!',},
];